// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation() {
  return window['go']['backend']['App']['CancelOperation']();
}

export function CheckSystemRequirements() {
  return window['go']['backend']['App']['CheckSystemRequirements']();
}

export function ClearData(arg1) {
  return window['go']['backend']['App']['ClearData'](arg1);
}

export function ConnectWirelessAdb(arg1, arg2) {
  return window['go']['backend']['App']['ConnectWirelessAdb'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['backend']['App']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['backend']['App']['DeleteFile'](arg1);
}

export function DeleteMultipleFiles(arg1) {
  return window['go']['backend']['App']['DeleteMultipleFiles'](arg1);
}

export function DisableMultiplePackages(arg1) {
  return window['go']['backend']['App']['DisableMultiplePackages'](arg1);
}

export function DisablePackage(arg1) {
  return window['go']['backend']['App']['DisablePackage'](arg1);
}

export function DisconnectWirelessAdb(arg1, arg2) {
  return window['go']['backend']['App']['DisconnectWirelessAdb'](arg1, arg2);
}

export function EnableMultiplePackages(arg1) {
  return window['go']['backend']['App']['EnableMultiplePackages'](arg1);
}

export function EnablePackage(arg1) {
  return window['go']['backend']['App']['EnablePackage'](arg1);
}

export function EnableWirelessAdb(arg1) {
  return window['go']['backend']['App']['EnableWirelessAdb'](arg1);
}

export function FlashPartition(arg1, arg2) {
  return window['go']['backend']['App']['FlashPartition'](arg1, arg2);
}

export function FlashRomFolder(arg1, arg2, arg3) {
  return window['go']['backend']['App']['FlashRomFolder'](arg1, arg2, arg3);
}

export function GetCommandHistory(arg1, arg2) {
  return window['go']['backend']['App']['GetCommandHistory'](arg1, arg2);
}

export function GetDeviceInfo() {
  return window['go']['backend']['App']['GetDeviceInfo']();
}

export function GetDeviceMode() {
  return window['go']['backend']['App']['GetDeviceMode']();
}

export function GetDevices() {
  return window['go']['backend']['App']['GetDevices']();
}

export function GetFastbootDevices() {
  return window['go']['backend']['App']['GetFastbootDevices']();
}

export function GetFastbootSlot(arg1) {
  return window['go']['backend']['App']['GetFastbootSlot'](arg1);
}

export function GetPerformanceSnapshot(arg1) {
  return window['go']['backend']['App']['GetPerformanceSnapshot'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['backend']['App']['InstallPackage'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['backend']['App']['ListFiles'](arg1);
}

export function ListPackages(arg1) {
  return window['go']['backend']['App']['ListPackages'](arg1);
}

export function PullApk(arg1) {
  return window['go']['backend']['App']['PullApk'](arg1);
}

export function PullFile(arg1, arg2) {
  return window['go']['backend']['App']['PullFile'](arg1, arg2);
}

export function PullMultipleFiles(arg1) {
  return window['go']['backend']['App']['PullMultipleFiles'](arg1);
}

export function PushFile(arg1, arg2) {
  return window['go']['backend']['App']['PushFile'](arg1, arg2);
}

export function Reboot(arg1) {
  return window['go']['backend']['App']['Reboot'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['backend']['App']['RenameFile'](arg1, arg2);
}

export function RunAdbHostCommand(arg1) {
  return window['go']['backend']['App']['RunAdbHostCommand'](arg1);
}

export function RunFastbootHostCommand(arg1) {
  return window['go']['backend']['App']['RunFastbootHostCommand'](arg1);
}

export function RunShellCommand(arg1) {
  return window['go']['backend']['App']['RunShellCommand'](arg1);
}

export function ScanRomFolder(arg1) {
  return window['go']['backend']['App']['ScanRomFolder'](arg1);
}

export function SelectApkFile() {
  return window['go']['backend']['App']['SelectApkFile']();
}

export function SelectDirectoryForPull() {
  return window['go']['backend']['App']['SelectDirectoryForPull']();
}

export function SelectDirectoryToPush() {
  return window['go']['backend']['App']['SelectDirectoryToPush']();
}

export function SelectFileToPush() {
  return window['go']['backend']['App']['SelectFileToPush']();
}

export function SelectFilesToPush() {
  return window['go']['backend']['App']['SelectFilesToPush']();
}

export function SelectFoldersToPush() {
  return window['go']['backend']['App']['SelectFoldersToPush']();
}

export function SelectImageFile() {
  return window['go']['backend']['App']['SelectImageFile']();
}

export function SelectSaveDirectory(arg1) {
  return window['go']['backend']['App']['SelectSaveDirectory'](arg1);
}

export function SelectSaveFile(arg1) {
  return window['go']['backend']['App']['SelectSaveFile'](arg1);
}

export function SelectZipFile() {
  return window['go']['backend']['App']['SelectZipFile']();
}

export function SetActiveSerial(arg1) {
  return window['go']['backend']['App']['SetActiveSerial'](arg1);
}

export function SetFastbootSlot(arg1, arg2) {
  return window['go']['backend']['App']['SetFastbootSlot'](arg1, arg2);
}

export function SideloadPackage(arg1) {
  return window['go']['backend']['App']['SideloadPackage'](arg1);
}

export function StartLogcat(arg1, arg2) {
  return window['go']['backend']['App']['StartLogcat'](arg1, arg2);
}

export function StopLogcat(arg1) {
  return window['go']['backend']['App']['StopLogcat'](arg1);
}

export function UninstallMultiplePackages(arg1) {
  return window['go']['backend']['App']['UninstallMultiplePackages'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['backend']['App']['UninstallPackage'](arg1);
}

export function WipeData() {
  return window['go']['backend']['App']['WipeData']();
}
