// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CancelOperation():Promise<string>;

export function CheckSystemRequirements():Promise<string>;

export function ClearData(arg1:string):Promise<string>;

export function ConnectWirelessAdb(arg1:string,arg2:string):Promise<string>;

export function CreateBugreport(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<string>;

export function DeleteMultipleFiles(arg1:Array<string>):Promise<string>;

export function DisableMultiplePackages(arg1:Array<string>):Promise<string>;

export function DisablePackage(arg1:string):Promise<string>;

export function DisconnectWirelessAdb(arg1:string,arg2:string):Promise<string>;

export function EnableMultiplePackages(arg1:Array<string>):Promise<string>;

export function EnablePackage(arg1:string):Promise<string>;

export function EnableWirelessAdb(arg1:string):Promise<string>;

export function FlashPartition(arg1:string,arg2:string):Promise<void>;

export function FlashRomFolder(arg1:string,arg2:string,arg3:backend.FlashPlan):Promise<void>;

export function GetCommandHistory(arg1:string,arg2:number):Promise<Array<backend.CommandLogEntry>>;

export function GetDeviceInfo():Promise<backend.DeviceInfo>;

export function GetDeviceMode():Promise<string>;

export function GetDevices():Promise<Array<backend.Device>>;

export function GetFastbootDevices():Promise<Array<backend.Device>>;

export function GetFastbootSlot(arg1:string):Promise<string>;

export function GetPerformanceSnapshot(arg1:string):Promise<backend.PerformanceSnapshot>;

export function Greet(arg1:string):Promise<string>;

export function InstallPackage(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<backend.FileEntry>>;

export function ListPackages(arg1:string):Promise<Array<backend.PackageInfo>>;

export function PullApk(arg1:string):Promise<string>;

export function PullFile(arg1:string,arg2:string):Promise<string>;

export function PullMultipleFiles(arg1:Array<string>):Promise<string>;

export function PushFile(arg1:string,arg2:string):Promise<string>;

export function Reboot(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function RunAdbHostCommand(arg1:string):Promise<string>;

export function RunFastbootHostCommand(arg1:string):Promise<string>;

export function RunShellCommand(arg1:string):Promise<string>;

export function ScanRomFolder(arg1:string):Promise<backend.FlashPlan>;

export function SelectApkFile():Promise<string>;

export function SelectDirectoryForPull():Promise<string>;

export function SelectDirectoryToPush():Promise<string>;

export function SelectFileToPush():Promise<string>;

export function SelectFilesToPush():Promise<Array<string>>;

export function SelectFoldersToPush():Promise<Array<string>>;

export function SelectImageFile():Promise<string>;

export function SelectSaveDirectory(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetActiveSerial(arg1:string):Promise<void>;

export function SetFastbootSlot(arg1:string,arg2:string):Promise<void>;

export function SideloadPackage(arg1:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:string):Promise<void>;

export function StopLogcat(arg1:string):Promise<void>;

export function UninstallMultiplePackages(arg1:Array<string>):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function WipeData():Promise<void>;
